export const CREATE_REMINDER = 'CREATE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const DELETE_ALL_REMINDERS_BY_DAY = 'DELETE_ALL_REMINDERS_BY_DAY';
